# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: contour
      image: docker.1ms.run/bitnami/contour:1.30.2-debian-12-r0
    - name: envoy
      image: docker.1ms.run/bitnami/envoy:1.31.5-debian-12-r0
    - name: nginx
      image: docker.1ms.run/bitnami/nginx:1.27.3-debian-12-r5
apiVersion: v2
appVersion: 1.30.2
dependencies:
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Contour is an open source Kubernetes ingress controller that works by deploying the Envoy proxy as a reverse proxy and load balancer.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/contour/img/contour-stack-220x234.png
keywords:
- ingress
- envoy
- contour
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: contour
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/contour
version: 19.5.2
