# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: kubeapps-apis
      image: docker.1ms.run/bitnami/kubeapps-apis:2.12.1-debian-12-r0
    - name: kubeapps-apprepository-controller
      image: docker.1ms.run/bitnami/kubeapps-apprepository-controller:2.12.1-debian-12-r0
    - name: kubeapps-asset-syncer
      image: docker.1ms.run/bitnami/kubeapps-asset-syncer:2.12.1-debian-12-r0
    - name: kubeapps-dashboard
      image: docker.1ms.run/bitnami/kubeapps-dashboard:2.12.1-debian-12-r0
    - name: kubeapps-oci-catalog
      image: docker.1ms.run/bitnami/kubeapps-oci-catalog:2.12.1-debian-12-r0
    - name: kubeapps-pinniped-proxy
      image: docker.1ms.run/bitnami/kubeapps-pinniped-proxy:2.12.1-debian-12-r0
    - name: nginx
      image: docker.1ms.run/bitnami/nginx:1.27.3-debian-12-r0
    - name: oauth2-proxy
      image: docker.1ms.run/bitnami/oauth2-proxy:7.7.1-debian-12-r4
apiVersion: v2
appVersion: 2.12.1
dependencies:
- condition: packaging.flux.enabled
  name: redis
  repository: oci://docker.1ms.run/bitnamicharts
  version: 20.x.x
- condition: packaging.helm.enabled
  name: postgresql
  repository: oci://docker.1ms.run/bitnamicharts
  version: 16.x.x
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Kubeapps is a web-based UI for launching and managing applications on Kubernetes. It allows users to deploy trusted applications and operators to control users access to the cluster.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/kubeapps/img/kubeapps-stack-220x234.png
keywords:
- helm
- dashboard
- service catalog
- deployment
kubeVersion: '>=1.21.0-0'
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: kubeapps
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/kubeapps
version: 17.1.1
