# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: harbor-adapter-trivy
      image: docker.1ms.run/bitnami/harbor-adapter-trivy:2.12.1-debian-12-r0
    - name: harbor-core
      image: docker.1ms.run/bitnami/harbor-core:2.12.1-debian-12-r0
    - name: harbor-exporter
      image: docker.1ms.run/bitnami/harbor-exporter:2.12.1-debian-12-r0
    - name: harbor-jobservice
      image: docker.1ms.run/bitnami/harbor-jobservice:2.12.1-debian-12-r0
    - name: harbor-portal
      image: docker.1ms.run/bitnami/harbor-portal:2.12.1-debian-12-r3
    - name: harbor-registry
      image: docker.1ms.run/bitnami/harbor-registry:2.12.1-debian-12-r0
    - name: harbor-registryctl
      image: docker.1ms.run/bitnami/harbor-registryctl:2.12.1-debian-12-r0
    - name: nginx
      image: docker.1ms.run/bitnami/nginx:1.27.3-debian-12-r2
    - name: os-shell
      image: docker.1ms.run/bitnami/os-shell:12-debian-12-r34
    - name: postgresql
      image: docker.1ms.run/bitnami/postgresql:14.15.0-debian-12-r6
apiVersion: v2
appVersion: 2.12.1
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://docker.1ms.run/bitnamicharts
  version: 20.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: oci://docker.1ms.run/bitnamicharts
  version: 16.x.x
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Harbor is an open source trusted cloud-native registry to store, sign, and scan content. It adds functionalities like security, identity, and management to the open source Docker distribution.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/harbor-core/img/harbor-core-stack-220x234.png
keywords:
- docker
- registry
- vulnerability
- scan
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: harbor
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/harbor
version: 24.1.6
