# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Forum
  licenses: Apache-2.0
  images: |
    - name: discourse
      image: docker.1ms.run/bitnami/discourse:3.3.3-debian-12-r0
    - name: os-shell
      image: docker.1ms.run/bitnami/os-shell:12-debian-12-r34
apiVersion: v2
appVersion: 3.3.3
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://docker.1ms.run/bitnamicharts
  version: 20.X.X
- condition: postgresql.enabled
  name: postgresql
  repository: oci://docker.1ms.run/bitnamicharts
  version: 16.X.X
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Discourse is an open source discussion platform with built-in moderation and governance systems that let discussion communities protect themselves from bad actors even without official moderators.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/discourse/img/discourse-stack-220x234.png
keywords:
- community
- forum
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
- email: username.taken@gmail.com
  name: paulczar
- email: preteluca@gmail.com
  name: lucaprete
name: discourse
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/discourse
version: 15.1.1
