# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: ApplicationServer
  licenses: Apache-2.0
  images: |
    - name: jmx-exporter
      image: docker.1ms.run/bitnami/jmx-exporter:1.1.0-debian-12-r1
    - name: os-shell
      image: docker.1ms.run/bitnami/os-shell:12-debian-12-r34
    - name: tomcat
      image: docker.1ms.run/bitnami/tomcat:10.1.34-debian-12-r0
apiVersion: v2
appVersion: 10.1.34
dependencies:
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Tomcat is an open-source web server designed to host and run Java-based web applications. It is a lightweight server with a good performance for applications running in production environments.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/tomcat/img/tomcat-stack-220x234.png
keywords:
- tomcat
- java
- http
- web
- application server
- jsp
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: tomcat
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/tomcat
version: 11.5.0
