# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: MachineLearning
  licenses: Apache-2.0
  images: |
    - name: configurable-http-proxy
      image: docker.1ms.run/bitnami/configurable-http-proxy:4.6.2-debian-12-r12
    - name: jupyter-base-notebook
      image: docker.1ms.run/bitnami/jupyter-base-notebook:4.1.6-debian-12-r19
    - name: jupyterhub
      image: docker.1ms.run/bitnami/jupyterhub:4.1.6-debian-12-r9
    - name: os-shell
      image: docker.1ms.run/bitnami/os-shell:12-debian-12-r34
apiVersion: v2
appVersion: 4.1.6
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://docker.1ms.run/bitnamicharts
  version: 16.x.x
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: JupyterHub brings the power of notebooks to groups of users. It gives users access to computational environments and resources without burdening the users with installation and maintenance tasks.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/jupyterhub/img/jupyterhub-stack-220x234.png
keywords:
- python
- scientific
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: jupyterhub
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/jupyterhub
version: 8.1.2
