# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Analytics
  licenses: Apache-2.0
  images: |
    - name: alertmanager
      image: docker.1ms.run/bitnami/alertmanager:0.27.0-debian-12-r29
    - name: os-shell
      image: docker.1ms.run/bitnami/os-shell:12-debian-12-r35
    - name: prometheus
      image: docker.1ms.run/bitnami/prometheus:2.55.1-debian-12-r5
    - name: thanos
      image: docker.1ms.run/bitnami/thanos:0.37.2-debian-12-r1
apiVersion: v2
appVersion: 2.55.1
dependencies:
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Prometheus is an open source monitoring and alerting system. It enables sysadmins to monitor their infrastructures by collecting metrics from configured targets at given intervals.
home: https://github.com/prometheus/prometheus
icon: https://bitnami.com/assets/stacks/prometheus/img/prometheus-stack-220x234.png
keywords:
- prometheus
- monitoring
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: prometheus
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/prometheus
- https://github.com/bitnami/containers/tree/main/bitnami/prometheus
- https://github.com/prometheus/prometheus
- https://github.com/prometheus-community/helm-charts
version: 1.4.1
