# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: apisix
      image: docker.1ms.run/bitnami/apisix:3.11.0-debian-12-r4
    - name: apisix-dashboard
      image: docker.1ms.run/bitnami/apisix-dashboard:3.0.1-debian-12-r52
    - name: apisix-ingress-controller
      image: docker.1ms.run/bitnami/apisix-ingress-controller:1.8.3-debian-12-r5
    - name: os-shell
      image: docker.1ms.run/bitnami/os-shell:12-debian-12-r35
apiVersion: v2
appVersion: 3.11.0
dependencies:
- name: etcd
  repository: oci://docker.1ms.run/bitnamicharts
  condition: etcd.enabled
  version: 10.x.x
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache APISIX is high-performance, real-time API Gateway. Features load balancing, dynamic upstream, canary release, circuit breaking, authentication, observability, amongst others.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/apisix/img/apisix-stack-220x234.png
keywords:
- apisix
- ingress
- openresty
- controller
- http
- web
- www
- reverse proxy
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: apisix
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/apisix
- https://github.com/bitnami/charts/tree/main/bitnami/apisix-dashboard
- https://github.com/bitnami/charts/tree/main/bitnami/apisix-ingress-controller
version: 3.7.1
