# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: CertificateAuthority
  licenses: Apache-2.0
  images: |
    - name: acmesolver
      image: docker.1ms.run/bitnami/acmesolver:1.16.2-debian-12-r3
    - name: cainjector
      image: docker.1ms.run/bitnami/cainjector:1.16.2-debian-12-r2
    - name: cert-manager
      image: docker.1ms.run/bitnami/cert-manager:1.16.2-debian-12-r2
    - name: cert-manager-webhook
      image: docker.1ms.run/bitnami/cert-manager-webhook:1.16.2-debian-12-r2
apiVersion: v2
appVersion: 1.16.2
dependencies:
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: cert-manager is a Kubernetes add-on to automate the management and issuance of TLS certificates from various issuing sources.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/cert-manager/img/cert-manager-stack-220x234.png
keywords:
- go
- security
- tls
- certificate
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: cert-manager
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/cert-manager
version: 1.4.1
