# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: grafana-tempo
      image: docker.1ms.run/bitnami/grafana-tempo:2.6.1-debian-12-r5
    - name: grafana-tempo-query
      image: docker.1ms.run/bitnami/grafana-tempo-query:2.6.1-debian-12-r5
    - name: grafana-tempo-vulture
      image: docker.1ms.run/bitnami/grafana-tempo-vulture:2.6.1-debian-12-r5
    - name: os-shell
      image: docker.1ms.run/bitnami/os-shell:12-debian-12-r35
apiVersion: v2
appVersion: 2.6.1
dependencies:
- condition: memcached.enabled
  name: memcached
  repository: oci://docker.1ms.run/bitnamicharts
  version: 7.x.x
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Grafana Tempo is a distributed tracing system that has out-of-the-box integration with Grafana. It is highly scalable and works with many popular tracing protocols.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/grafana-tempo/img/grafana-tempo-stack-220x234.png
keywords:
- grafana
- tracing
- metrics
- infrastructure
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: grafana-tempo
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/grafana-tempo
version: 3.8.1
