# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: DeveloperTools
  licenses: Apache-2.0
  images: |
    - name: jmx-exporter
      image: docker.1ms.run/bitnami/jmx-exporter:1.1.0-debian-12-r1
    - name: os-shell
      image: docker.1ms.run/bitnami/os-shell:12-debian-12-r35
    - name: sonarqube
      image: docker.1ms.run/bitnami/sonarqube:25.1.0-debian-12-r1
apiVersion: v2
appVersion: 25.1.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://docker.1ms.run/bitnamicharts
  version: 16.x.x
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: SonarQube(TM) is an open source quality management platform that analyzes and measures code's technical quality. It enables developers to detect code issues, vulnerabilities, and bugs in early stages.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/sonarqube/img/sonarqube-stack-220x234.png
keywords:
- sonarqube
- code-quality
- code-review
- static-analysis
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: sonarqube
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/sonarqube
version: 8.0.1
