# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Analytics
  licenses: Apache-2.0
  images: |
    - name: apache-exporter
      image: docker.1ms.run/bitnami/apache-exporter:1.0.9-debian-12-r6
    - name: matomo
      image: docker.1ms.run/bitnami/matomo:5.2.1-debian-12-r0
    - name: os-shell
      image: docker.1ms.run/bitnami/os-shell:12-debian-12-r34
apiVersion: v2
appVersion: 5.2.1
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: oci://docker.1ms.run/bitnamicharts
  version: 20.x.x
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Matomo, formerly known as Piwik, is a real time web analytics program. It provides detailed reports on website visitors.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/matomo/img/matomo-stack-220x234.png
keywords:
- matomo
- analytics
- http
- web
- application
- php
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: matomo
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/matomo
version: 9.2.1
