# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: attu
      image: docker.1ms.run/bitnami/attu:2.5.0-debian-12-r0
    - name: milvus
      image: docker.1ms.run/bitnami/milvus:2.5.3-debian-12-r0
    - name: os-shell
      image: docker.1ms.run/bitnami/os-shell:12-debian-12-r35
    - name: pymilvus
      image: docker.1ms.run/bitnami/pymilvus:2.5.3-debian-12-r0
apiVersion: v2
appVersion: 2.5.3
dependencies:
- name: etcd
  repository: oci://docker.1ms.run/bitnamicharts
  condition: etcd.enabled
  version: 10.x.x
- condition: kafka.enabled
  name: kafka
  repository: oci://docker.1ms.run/bitnamicharts
  version: 31.x.x
- condition: minio.enabled
  name: minio
  repository: oci://docker.1ms.run/bitnamicharts
  version: 14.x.x
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Milvus is a cloud-native, open-source vector database solution for AI applications and similarity search. Features high scalability, hibrid search and unified lambda structure.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/milvus/img/milvus-stack-220x234.png
keywords:
- milvus
- ai
- database
- infrastructure
- attu
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: milvus
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/milvus
version: 10.1.4
