# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: WorkFlow
  licenses: Apache-2.0
  images: |
    - name: airflow
      image: docker.1ms.run/bitnami/airflow:2.10.4-debian-12-r2
    - name: statsd-exporter
      image: docker.1ms.run/bitnami/statsd-exporter:0.28.0-debian-12-r2
apiVersion: v2
appVersion: 2.10.4
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://docker.1ms.run/bitnamicharts
  version: 20.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: oci://docker.1ms.run/bitnamicharts
  version: 16.x.x
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Airflow is a tool to express and execute workflows as directed acyclic graphs (DAGs). It includes utilities to schedule tasks, monitor task progress and handle task dependencies.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/airflow/img/airflow-stack-220x234.png
keywords:
- apache
- airflow
- workflow
- dag
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: airflow
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/airflow
version: 22.4.5
