# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: minio
      image: docker.1ms.run/bitnami/minio:2024.12.18-debian-12-r0
    - name: minio-client
      image: docker.1ms.run/bitnami/minio-client:2024.11.21-debian-12-r1
    - name: os-shell
      image: docker.1ms.run/bitnami/os-shell:12-debian-12-r34
apiVersion: v2
appVersion: 2024.12.18
dependencies:
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: MinIO(R) is an object storage server, compatible with Amazon S3 cloud storage service, mainly used for storing unstructured data (such as photos, videos, log files, etc.).
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/minio/img/minio-stack-220x234.png
keywords:
- minio
- storage
- object-storage
- s3
- cluster
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: minio
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/minio
version: 14.10.3
