# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Analytics
  licenses: Apache-2.0
  images: |
    - name: dremio
      image: docker.1ms.run/bitnami/dremio:25.2.0-debian-12-r1
    - name: jmx-exporter
      image: docker.1ms.run/bitnami/jmx-exporter:1.1.0-debian-12-r1
    - name: os-shell
      image: docker.1ms.run/bitnami/os-shell:12-debian-12-r33
apiVersion: v2
appVersion: 25.2.0
dependencies:
- condition: minio.enabled
  name: minio
  repository: oci://docker.1ms.run/bitnamicharts
  version: 14.x.x
- condition: zookeeper.enabled
  name: zookeeper
  repository: oci://docker.1ms.run/bitnamicharts
  version: 13.x.x
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Dremio is an open-source self-service data access tool that provides high-performance queries for interactive analytics on data lakes.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/dremio/img/dremio-stack-220x234.png
keywords:
- dremio
- data-lake
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: dremio
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/dremio
- https://github.com/bitnami/containers/tree/main/bitnami/dremio
- https://github.com/dremio/dremio-oss
version: 0.3.0
