# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: fluxcd-helm-controller
      image: docker.1ms.run/bitnami/fluxcd-helm-controller:1.1.0-debian-12-r6
    - name: fluxcd-image-automation-controller
      image: docker.1ms.run/bitnami/fluxcd-image-automation-controller:0.39.0-debian-12-r6
    - name: fluxcd-image-reflector-controller
      image: docker.1ms.run/bitnami/fluxcd-image-reflector-controller:0.33.0-debian-12-r6
    - name: fluxcd-kustomize-controller
      image: docker.1ms.run/bitnami/fluxcd-kustomize-controller:1.4.0-debian-12-r6
    - name: fluxcd-notification-controller
      image: docker.1ms.run/bitnami/fluxcd-notification-controller:1.4.0-debian-12-r7
    - name: fluxcd-source-controller
      image: docker.1ms.run/bitnami/fluxcd-source-controller:1.4.1-debian-12-r6
    - name: os-shell
      image: docker.1ms.run/bitnami/os-shell:12-debian-12-r35
apiVersion: v2
appVersion: 1.4.1
dependencies:
- name: common
  repository: oci://docker.1ms.run/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Source Controller is a component of Flux. Flux is a tool for keeping Kubernetes clusters in sync with sources of configuration.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/fluxcd-kustomize-controller/img/fluxcd-kustomize-controller-stack-220x234.png
keywords:
- deployment
- gitops
- cd
- continuous-delivery
- helm
- kustomize
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: flux
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/flux
version: 2.4.1
